### ISSUE TITLE
Submit package to CRAN

### ISSUE THREAD

**Issue by parmsam** [ashbaldry/designer#17]
Happy to help wherever I can to get the package on CRAN. 
- https://r-pkgs.org/release.html
- https://kbroman.org/pkg_primer/pages/cran.html

**Comment by ashbaldry** [comment]
Thanks for the offer. I've done some refactoring tonight as there was a fair amount of code duplication in places. 

The application I feel is now pretty stable, but I want to get a bit more documentation in place (in the `designApp` function and update the README) before submitting to CRAN. If you can think of anything to include in the README that I've excluded would be helpful!

**Comment by parmsam** [comment]
Just added note about the Rstudio Addin to the README. I can help with vignettes in the near future. That will be great for first-time users. I'll create an issue for a first vignette.
