### ISSUE TITLE
customize code filename

### ISSUE THREAD

**Issue by parmsam** [ashbaldry/designer#42]
allow user to decide ui code filename

**Comment by ashbaldry** [comment]
Whilst for standard shiny applications I'm not sure of the use of a different filename, it would be good to include this with a way to have a function for `{golem}` based applications.

**Comment by parmsam** [comment]
Yes, that's a good point. Golem apps also use the "app_ui.R" naming by default. Module UI development would be an interesting exploration area. Should that be another issue?

**Comment by ashbaldry** [comment]
Yes it should, created #47.

When customizing the name, also need to think about other structures like the {rhino} package
