### ISSUE TITLE
Add example usage gif image to the README

### ISSUE THREAD

**Issue by parmsam** [ashbaldry/designer#8]
Would be helpful to first time users to easily see how to use the app. Probably for future release after package is more stable.

**Comment by parmsam** [comment]
The ffmpeg is a useful command line tool for this: 
- https://linuxhint.com/convert-video-to-gif-linux/
- https://askubuntu.com/questions/648603/how-to-create-an-animated-gif-from-mp4-video-via-command-line

**Comment by ashbaldry** [comment]
Let me know your thoughts on the current gif - tried not to make it too long

**Comment by parmsam** [comment]
Agreed that we prob want to keep it short. The esquisse README has a [great reference GIF](https://github.com/dreamRs/esquisse/blob/master/man/figures/esquisse.gif) that shows many features. It's longer, but it is very helpful to a first time user. In this case, we might incorporate more features to recreate an example UI that could be used in practice ([example simple app](https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/)).
